<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $secureRenderer \Magento\Framework\View\Helper\SecureHtmlRenderer
 * @var $hyvaThemeDetection \MageOS\Blog\Api\HyvaThemeDetectionInterface
 */
?>
<?php if (!$hyvaThemeDetection->execute()) { ?>

    <?php $script = "
        require(['jquery', 'domReady!'], function($){
            if ($('.mageos_blogunveil').length) {
                require(['MageOS_Blog/js/lib/mageos_blogunveil'], function(){
                    $('.mageos_blogunveil').mageos_blogunveil();
                });
            }
        });
    "; ?>

<?php } else { ?>

    <?php $script = "
        /* e.g. hyva theme */
        document.addEventListener('DOMContentLoaded', function(){
            var items =  document.getElementsByClassName('mageos_blogunveil');
            var el, url;
            if (items.length) {
                for (var i=0; i<items.length;i++) {
                    el = items[i];
                    url = el.getAttribute('data-original');
                    if (!url) {
                        continue;
                    };
                    if ('IMG' == el.tagName) {
                        el.src = url;
                    } else {
                        el.style.backgroundImage = \"url('\" + url  + \"')\";
                    }
                }
            }
        });
    "; ?>

<?php } ?>

<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $script, false) ?>

