<?php

declare(strict_types=1);

namespace MageOS\Blog\Plugin\Repository\Category;

use Magento\UrlRewrite\Model\OptionProvider;
use Magento\UrlRewrite\Model\UrlFinderInterface;
use Magento\UrlRewrite\Model\UrlPersistInterface;
use Magento\UrlRewrite\Service\V1\Data\UrlRewrite;
use Magento\UrlRewrite\Service\V1\Data\UrlRewriteFactory;
use MageOS\Blog\Api\CategoryRepositoryInterface;
use MageOS\Blog\Api\Data\CategoryInterface;
use MageOS\Blog\Model\Url\UrlRewriteBuilder;

class UrlRewritePlugin
{
    public function __construct(
        private readonly UrlRewriteBuilder $urlRewriteBuilder,
        private readonly UrlPersistInterface $urlPersist,
        private readonly UrlFinderInterface $urlFinder,
        private readonly UrlRewriteFactory $urlRewriteFactory,
    ) {
    }

    public function afterSave(
        CategoryRepositoryInterface $subject,
        CategoryInterface $result,
    ): CategoryInterface {
        $storeIds = $result->getStoreIds();
        if ($storeIds === []) {
            return $result;
        }

        $categoryId = (int) $result->getCategoryId();
        $newRows = $this->urlRewriteBuilder->buildForCategory($result, $storeIds);
        $newRequestPath = 'blog/category/' . $result->getUrlKey();
        $newTargetPath = 'blog/category/view/id/' . $categoryId;

        $redirectRows = $this->buildRedirectsForChangedSlug(
            $categoryId,
            $newRequestPath,
            $newTargetPath,
        );

        $this->urlPersist->replace(array_merge($redirectRows, $newRows));

        return $result;
    }

    public function afterDelete(
        CategoryRepositoryInterface $subject,
        bool $result,
        CategoryInterface $category,
    ): bool {
        $this->urlPersist->deleteByData([
            UrlRewrite::ENTITY_TYPE => UrlRewriteBuilder::ENTITY_TYPE_CATEGORY,
            UrlRewrite::ENTITY_ID => (int) $category->getCategoryId(),
        ]);

        return $result;
    }

    public function afterDeleteById(
        CategoryRepositoryInterface $subject,
        bool $result,
        int $id,
    ): bool {
        $this->urlPersist->deleteByData([
            UrlRewrite::ENTITY_TYPE => UrlRewriteBuilder::ENTITY_TYPE_CATEGORY,
            UrlRewrite::ENTITY_ID => $id,
        ]);

        return $result;
    }

    /**
     * @return UrlRewrite[]
     */
    private function buildRedirectsForChangedSlug(
        int $categoryId,
        string $newRequestPath,
        string $newTargetPath,
    ): array {
        $existing = $this->urlFinder->findAllByData([
            UrlRewrite::ENTITY_TYPE => UrlRewriteBuilder::ENTITY_TYPE_CATEGORY,
            UrlRewrite::ENTITY_ID => $categoryId,
            UrlRewrite::REDIRECT_TYPE => 0,
        ]);

        $redirects = [];
        $seen = [];
        foreach ($existing as $row) {
            $oldPath = (string) $row->getRequestPath();
            if ($oldPath === '' || $oldPath === $newRequestPath) {
                continue;
            }
            $storeId = (int) $row->getStoreId();
            $key = $storeId . '|' . $oldPath;
            if (isset($seen[$key])) {
                continue;
            }
            $seen[$key] = true;

            $redirect = $this->urlRewriteFactory->create();
            $redirect->setEntityType(UrlRewriteBuilder::ENTITY_TYPE_CATEGORY)
                ->setEntityId($categoryId)
                ->setRequestPath($oldPath)
                ->setTargetPath($newTargetPath)
                ->setIsAutogenerated(0)
                ->setStoreId($storeId)
                ->setRedirectType(OptionProvider::PERMANENT);
            $redirects[] = $redirect;
        }

        return $redirects;
    }
}
