<?php

declare(strict_types=1);

namespace MageOS\Blog\Plugin\Repository\Author;

use Magento\UrlRewrite\Model\OptionProvider;
use Magento\UrlRewrite\Model\UrlFinderInterface;
use Magento\UrlRewrite\Model\UrlPersistInterface;
use Magento\UrlRewrite\Service\V1\Data\UrlRewrite;
use Magento\UrlRewrite\Service\V1\Data\UrlRewriteFactory;
use MageOS\Blog\Api\AuthorRepositoryInterface;
use MageOS\Blog\Api\Data\AuthorInterface;
use MageOS\Blog\Model\Url\UrlRewriteBuilder;

class UrlRewritePlugin
{
    public function __construct(
        private readonly UrlRewriteBuilder $urlRewriteBuilder,
        private readonly UrlPersistInterface $urlPersist,
        private readonly UrlFinderInterface $urlFinder,
        private readonly UrlRewriteFactory $urlRewriteFactory,
    ) {
    }

    public function afterSave(
        AuthorRepositoryInterface $subject,
        AuthorInterface $result,
    ): AuthorInterface {
        $authorId = (int) $result->getAuthorId();
        $newRows = $this->urlRewriteBuilder->buildForAuthor($result);
        $newRequestPath = 'blog/author/' . $result->getSlug();
        $newTargetPath = 'blog/author/view/id/' . $authorId;

        $redirectRows = $this->buildRedirectsForChangedSlug(
            $authorId,
            $newRequestPath,
            $newTargetPath,
        );

        $this->urlPersist->replace(array_merge($redirectRows, $newRows));

        return $result;
    }

    public function afterDelete(
        AuthorRepositoryInterface $subject,
        bool $result,
        AuthorInterface $author,
    ): bool {
        $this->urlPersist->deleteByData([
            UrlRewrite::ENTITY_TYPE => UrlRewriteBuilder::ENTITY_TYPE_AUTHOR,
            UrlRewrite::ENTITY_ID => (int) $author->getAuthorId(),
        ]);

        return $result;
    }

    public function afterDeleteById(
        AuthorRepositoryInterface $subject,
        bool $result,
        int $id,
    ): bool {
        $this->urlPersist->deleteByData([
            UrlRewrite::ENTITY_TYPE => UrlRewriteBuilder::ENTITY_TYPE_AUTHOR,
            UrlRewrite::ENTITY_ID => $id,
        ]);

        return $result;
    }

    /**
     * @return UrlRewrite[]
     */
    private function buildRedirectsForChangedSlug(
        int $authorId,
        string $newRequestPath,
        string $newTargetPath,
    ): array {
        $existing = $this->urlFinder->findAllByData([
            UrlRewrite::ENTITY_TYPE => UrlRewriteBuilder::ENTITY_TYPE_AUTHOR,
            UrlRewrite::ENTITY_ID => $authorId,
            UrlRewrite::REDIRECT_TYPE => 0,
        ]);

        $redirects = [];
        $seen = [];
        foreach ($existing as $row) {
            $oldPath = (string) $row->getRequestPath();
            if ($oldPath === '' || $oldPath === $newRequestPath) {
                continue;
            }
            $storeId = (int) $row->getStoreId();
            $key = $storeId . '|' . $oldPath;
            if (isset($seen[$key])) {
                continue;
            }
            $seen[$key] = true;

            $redirect = $this->urlRewriteFactory->create();
            $redirect->setEntityType(UrlRewriteBuilder::ENTITY_TYPE_AUTHOR)
                ->setEntityId($authorId)
                ->setRequestPath($oldPath)
                ->setTargetPath($newTargetPath)
                ->setIsAutogenerated(0)
                ->setStoreId($storeId)
                ->setRedirectType(OptionProvider::PERMANENT);
            $redirects[] = $redirect;
        }

        return $redirects;
    }
}
