<?php
/**
 * @var $block \MageOS\Blog\Block\ViewsCount
 * @var $secureRenderer \Magento\Framework\View\Helper\SecureHtmlRenderer
 */
?>
<?php $script = "
    require(['jquery', 'domReady!'], function($){
        setTimeout(function(){
            $.ajax({
                url: atob( '" . base64_encode($block->getCounterUrl()) . "'),
                type:'POST',
                dataType: 'json',
                success: function(response) { }
            })
        }, 5000);
    });
"; ?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $script, false) ?>

