<?php /** @var $secureRenderer \Magento\Framework\View\Helper\SecureHtmlRenderer */ ?>

<?php $script = "
    require(['jquery', 'domReady!'], function ($) {
        var isLoadedInterval = setInterval(isLoaded, 2000);

        function isLoaded() {
            var el = $('[data-index=\"related\"] .admin__data-grid-pager-wrap');

            if (el.length) {
                $('[data-index=\"related\"] .admin__data-grid-pager-wrap').click(function () {
                    $('[data-index=\"related\"] [data-role=\"spinner\"]').show();
                    setTimeout(function () {
                        $('[data-index=\"related\"] [data-role=\"spinner\"]').hide();
                    }, 5000);
                });

                clearInterval(isLoadedInterval);
            }
        }
    });
"; ?>

<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $script, false) ?>
