<?php

declare(strict_types=1);

namespace MageOS\Blog\Model\Url;

use Magento\Store\Model\StoreManagerInterface;
use Magento\UrlRewrite\Service\V1\Data\UrlRewrite;
use Magento\UrlRewrite\Service\V1\Data\UrlRewriteFactory;
use MageOS\Blog\Api\Data\AuthorInterface;
use MageOS\Blog\Api\Data\CategoryInterface;
use MageOS\Blog\Api\Data\PostInterface;
use MageOS\Blog\Api\Data\TagInterface;

class UrlRewriteBuilder
{
    public const ENTITY_TYPE_POST = 'mageos_blog_post';
    public const ENTITY_TYPE_CATEGORY = 'mageos_blog_category';
    public const ENTITY_TYPE_TAG = 'mageos_blog_tag';
    public const ENTITY_TYPE_AUTHOR = 'mageos_blog_author';

    public function __construct(
        private readonly UrlRewriteFactory $urlRewriteFactory,
        private readonly StoreManagerInterface $storeManager,
    ) {
    }

    /**
     * @param int[] $storeIds
     * @return UrlRewrite[]
     */
    public function buildForPost(PostInterface $post, array $storeIds): array
    {
        $postId = (int) $post->getPostId();
        $requestPath = $this->postRequestPath($post->getUrlKey());
        $targetPath = 'blog/post/view/id/' . $postId;

        return $this->buildRows(
            self::ENTITY_TYPE_POST,
            $postId,
            $requestPath,
            $targetPath,
            $this->expandStoreIds($storeIds),
        );
    }

    /**
     * @param int[] $storeIds
     * @return UrlRewrite[]
     */
    public function buildForCategory(CategoryInterface $category, array $storeIds): array
    {
        $categoryId = (int) $category->getCategoryId();
        $requestPath = $this->categoryRequestPath($category->getUrlKey());
        $targetPath = 'blog/category/view/id/' . $categoryId;

        return $this->buildRows(
            self::ENTITY_TYPE_CATEGORY,
            $categoryId,
            $requestPath,
            $targetPath,
            $this->expandStoreIds($storeIds),
        );
    }

    /**
     * @param int[] $storeIds
     * @return UrlRewrite[]
     */
    public function buildForTag(TagInterface $tag, array $storeIds): array
    {
        $tagId = (int) $tag->getTagId();
        $requestPath = $this->tagRequestPath($tag->getUrlKey());
        $targetPath = 'blog/tag/view/id/' . $tagId;

        return $this->buildRows(
            self::ENTITY_TYPE_TAG,
            $tagId,
            $requestPath,
            $targetPath,
            $this->expandStoreIds($storeIds),
        );
    }

    /**
     * @return UrlRewrite[]
     */
    public function buildForAuthor(AuthorInterface $author): array
    {
        $authorId = (int) $author->getAuthorId();
        $requestPath = $this->authorRequestPath($author->getSlug());
        $targetPath = 'blog/author/view/id/' . $authorId;

        return $this->buildRows(
            self::ENTITY_TYPE_AUTHOR,
            $authorId,
            $requestPath,
            $targetPath,
            $this->allActiveStoreIds(),
        );
    }

    /**
     * @param int[] $storeIds
     * @return UrlRewrite[]
     */
    private function buildRows(
        string $entityType,
        int $entityId,
        string $requestPath,
        string $targetPath,
        array $storeIds,
    ): array {
        $rows = [];
        foreach ($storeIds as $storeId) {
            $rewrite = $this->urlRewriteFactory->create();
            $rewrite->setEntityType($entityType)
                ->setEntityId($entityId)
                ->setRequestPath($requestPath)
                ->setTargetPath($targetPath)
                ->setIsAutogenerated(1)
                ->setStoreId($storeId)
                ->setRedirectType(0);
            $rows[] = $rewrite;
        }

        return $rows;
    }

    /**
     * @param int[] $storeIds
     * @return int[]
     */
    private function expandStoreIds(array $storeIds): array
    {
        $normalized = array_values(array_unique(array_map('intval', $storeIds)));
        if (\in_array(0, $normalized, true)) {
            return $this->allActiveStoreIds();
        }

        return $normalized;
    }

    /**
     * @return int[]
     */
    private function allActiveStoreIds(): array
    {
        $ids = [];
        foreach ($this->storeManager->getStores(true) as $store) {
            $ids[] = (int) $store->getId();
        }

        return $ids;
    }

    private function postRequestPath(string $urlKey): string
    {
        return 'blog/' . $urlKey;
    }

    private function categoryRequestPath(string $urlKey): string
    {
        return 'blog/category/' . $urlKey;
    }

    private function tagRequestPath(string $urlKey): string
    {
        return 'blog/tag/' . $urlKey;
    }

    private function authorRequestPath(string $slug): string
    {
        return 'blog/author/' . $slug;
    }
}
