<?php

declare(strict_types=1);

namespace MageOS\Blog\Plugin\Repository\Post;

use Magento\UrlRewrite\Model\OptionProvider;
use Magento\UrlRewrite\Model\UrlFinderInterface;
use Magento\UrlRewrite\Model\UrlPersistInterface;
use Magento\UrlRewrite\Service\V1\Data\UrlRewrite;
use Magento\UrlRewrite\Service\V1\Data\UrlRewriteFactory;
use MageOS\Blog\Api\Data\PostInterface;
use MageOS\Blog\Api\PostRepositoryInterface;
use MageOS\Blog\Model\Url\UrlRewriteBuilder;

class UrlRewritePlugin
{
    public function __construct(
        private readonly UrlRewriteBuilder $urlRewriteBuilder,
        private readonly UrlPersistInterface $urlPersist,
        private readonly UrlFinderInterface $urlFinder,
        private readonly UrlRewriteFactory $urlRewriteFactory,
    ) {
    }

    public function afterSave(PostRepositoryInterface $subject, PostInterface $result): PostInterface
    {
        $storeIds = $result->getStoreIds();
        if ($storeIds === []) {
            return $result;
        }

        $postId = (int) $result->getPostId();
        $newRows = $this->urlRewriteBuilder->buildForPost($result, $storeIds);
        $newRequestPath = 'blog/' . $result->getUrlKey();
        $newTargetPath = 'blog/post/view/id/' . $postId;

        $redirectRows = $this->buildRedirectsForChangedSlug(
            $postId,
            $newRequestPath,
            $newTargetPath,
        );

        $this->urlPersist->replace(array_merge($redirectRows, $newRows));

        return $result;
    }

    public function afterDelete(PostRepositoryInterface $subject, bool $result, PostInterface $post): bool
    {
        $this->urlPersist->deleteByData([
            UrlRewrite::ENTITY_TYPE => UrlRewriteBuilder::ENTITY_TYPE_POST,
            UrlRewrite::ENTITY_ID => (int) $post->getPostId(),
        ]);

        return $result;
    }

    public function afterDeleteById(PostRepositoryInterface $subject, bool $result, int $id): bool
    {
        $this->urlPersist->deleteByData([
            UrlRewrite::ENTITY_TYPE => UrlRewriteBuilder::ENTITY_TYPE_POST,
            UrlRewrite::ENTITY_ID => $id,
        ]);

        return $result;
    }

    /**
     * @return UrlRewrite[]
     */
    private function buildRedirectsForChangedSlug(
        int $postId,
        string $newRequestPath,
        string $newTargetPath,
    ): array {
        $existing = $this->urlFinder->findAllByData([
            UrlRewrite::ENTITY_TYPE => UrlRewriteBuilder::ENTITY_TYPE_POST,
            UrlRewrite::ENTITY_ID => $postId,
            UrlRewrite::REDIRECT_TYPE => 0,
        ]);

        $redirects = [];
        $seen = [];
        foreach ($existing as $row) {
            $oldPath = (string) $row->getRequestPath();
            if ($oldPath === '' || $oldPath === $newRequestPath) {
                continue;
            }
            $storeId = (int) $row->getStoreId();
            $key = $storeId . '|' . $oldPath;
            if (isset($seen[$key])) {
                continue;
            }
            $seen[$key] = true;

            $redirect = $this->urlRewriteFactory->create();
            $redirect->setEntityType(UrlRewriteBuilder::ENTITY_TYPE_POST)
                ->setEntityId($postId)
                ->setRequestPath($oldPath)
                ->setTargetPath($newTargetPath)
                ->setIsAutogenerated(0)
                ->setStoreId($storeId)
                ->setRedirectType(OptionProvider::PERMANENT);
            $redirects[] = $redirect;
        }

        return $redirects;
    }
}
